# Configures whether villagers and wandering traders can be leashed
leashable_villagers = true
# Configures whether hostile mobs can be leashed
leashable_hostiles = false
# Configures whether water creatures (fish and squid) can be leashed
leashable_watercreatures = true
# Configures whether turtles can be leashed
leashable_turtles = true
# Configures whether ambient mobs (bats) can be leashed
leashable_ambients = false
# Configures whether pandas can be leashed
leashable_pandas = false
