!!com.github.einjerjar.mc.keymap.KeymapConfig
autoSelectLayout: true
customLayout: en_us
debug: false
keyButtonMalilibKeybinds: true
keyButtonModName: true
keybindKeyOnHover: true
keybindNameOnHover: true
malilibSupport: true
replaceKeybindScreen: true
