# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				panda = true
				bee = true
				axolotl = true
				egg = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				llama = true
				bat = true
				hoglin = true
				experience_bottle = true
				rabbit = true
				silverfish = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				stray = true
				turtle = true
				shulker = true
				wandering_trader = true
				salmon = true
				wither_skeleton = true
				piglin_brute = true
				goat = true
				ocelot = true
				item_frame = true
				horse = true
				vindicator = true
				phantom = true
				ender_dragon = true
				evoker = true
				llama_spit = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				chicken = true
				ravager = true
				trader_llama = true
				donkey = true
				fox = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				iron_golem = true
				zombified_piglin = true
				area_effect_cloud = true
				piglin = true
				blaze = true
				endermite = true
				cat = true
				zombie = true
				ender_pearl = true
				guardian = true
				ghast = true
				sheep = true
				player = true
				illusioner = true
				pufferfish = true
				trident = true
				wolf = true
				villager = true
				zombie_villager = true
				tnt_minecart = true
				elder_guardian = true
				boat = true
				polar_bear = true
				strider = true
				cave_spider = true
				cod = true
				witch = true
				spider = true

			[light_sources.settings.entities.impaled]
				hellfork = true
				soulfork = true
				pitchfork = true

			[light_sources.settings.entities.probablychests]
				stone_chest_mimic = true
				gold_chest_mimic = true
				lush_chest_mimic = true
				normal_chest_mimic = true
				rocky_chest_mimic = true

			[light_sources.settings.entities.pickyourpoison]
				poison_dart = true
				poison_dart_frog = true

			[light_sources.settings.entities.ratsmischief]
				rat = true

			[light_sources.settings.entities.creeperspores]
				creeperling = true

			[light_sources.settings.entities.additionaladditions]
				glow_stick = true

			[light_sources.settings.entities.friendsandfoes]
				glare = true
				copper_golem = true
				moobloom = true
				mauler = true
				iceologer = true

			[light_sources.settings.entities.blast]
				dirt_trigger_bomb = true
				dirt_bomb = true
				pearl_trigger_bomb = true
				stripminer = true
				confetti_trigger_bomb = true
				amethyst_trigger_bomb = true
				diamond_bomb = true
				diamond_trigger_bomb = true
				slime_trigger_bomb = true
				golden_trigger_bomb = true
				confetti_bomb = true
				pearl_bomb = true
				frost_trigger_bomb = true
				trigger_bomb = true
				slime_bomb = true
				amethyst_shard = true
				naval_mine = true
				amethyst_bomb = true
				golden_bomb = true
				frost_bomb = true
				icicle = true

