
#General Config Section
[general]
	#The Application ID of the Discord App to use
	clientID = 957576051192631327
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Enable/Disable the in game config screen
	configScreen = true
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Internal Version Number. NO TOUCHY!
	version = 13

#The Game Loading event
[init]
	#Enable/Disable the Game Loading Event
	enabled = true
	#The first line of text under the app name
	description = "Minecraft %mcver%"
	#The second line of text under the app name
	state = "Game is loading"
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo-overworld"
	#The text that gets displayed when the large image is hovered
	largeImageText = ""
	#The Asset ID of the image to display as the small image
	smallImageKey = "fabric"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"

	#The buttons to display on Discord
	[[init.buttons]]
		label = "Join Discord"
		url = "http://cubicdiscord.ga"

	[[init.buttons]]
		label = "Website"
		url = "https://cubic-inc.ga"

#The Main Menu event
[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true
	#The first line of text under the app name
	description = "Minecraft %mcver%"
	#The seconds line of text under the app name
	state = "In the menus"
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo-overworld"
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but modded"
	#The Asset ID of the image to display as the small image
	smallImageKey = "fabric"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
	buttons = []

#The Server List event
[server_list]
	#Enable/Disable the Server List Event
	enabled = true
	#The first line of text under the app name
	description = "Minecraft %mcver%"
	#The second line of text under the app name
	state = "In the server list"
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo-overworld"
	#The text that gets displayed when the large image is hovered
	largeImageText = ""
	#The Asset ID of the image to display as the small image
	smallImageKey = "fabric"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
	buttons = []

#The Realms Screen event
[realms_list]
	#Enable/Disable the Realms Screen Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is looking for a Realm"
	#The second line of text under the app name
	state = "Browsing Realms"
	#The Asset ID of the image to display as the large image
	largeImageKey = "mclogonew"
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but modded"
	#The Asset ID of the image to display as the small image
	smallImageKey = "mclogo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
	buttons = []

#The Join Game Event
[join_game]
	#Enable/Disable the Join Game Event
	enabled = true
	#The first line of text under the app name
	description = "Minecraft %mcver%"
	#The second line of text under the app name
	state = "Joining Game"
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo-overworld"
	#The text that gets displayed when the large image is hovered
	largeImageText = ""
	#The Asset ID of the image to display as the small image
	smallImageKey = "fabric"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
	buttons = []

#The Single Player Event
[single_player]
	#Enable/Disable the Single Player Event
	enabled = true
	#The first line of text under the app name
	description = "Minecraft %mcver%"
	#The second line of text under the app name
	state = "Playing lonely mode"
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo-overworld"
	#The text that gets displayed when the large image is hovered
	largeImageText = ""
	#The Asset ID of the image to display as the small image
	smallImageKey = "fabric"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
	buttons = []

#The Multi Player Event
[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = "Minecraft %mcver%"
	#The second line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo-overworld"
	#The text that gets displayed when the large image is hovered
	largeImageText = ""
	#The Asset ID of the image to display as the small image
	smallImageKey = "fabric"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
	buttons = []

#The Realms Game Event
[realms]
	#Enable/Disable the Realms Game Event
	enabled = true
	#The first line of text under the app name
	description = "Playing on %realmname%"
	#The second line of text under the app name
	state = "Playing on a Realm"
	#The Asset ID of the image to display as the large image
	largeImageKey = "mclogonew"
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but modded"
	#The Asset ID of the image to display as the small image
	smallImageKey = "mclogo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%realmdescription%"
	#The buttons to display on Discord
	buttons = []

#Fallback event for disabled events
[generic]
	#The first line of text under the app name
	description = "Minecraft %mcver%"
	#The second line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = "mclogonew"
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but modded"
	#The Asset ID of the image to display as the small image
	smallImageKey = "mclogo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
	buttons = []

#Dimension Information Overrides
[dimension_overrides]
	#Allows you to override the displayed values for dimensions
	enabled = true

	#The Dimensions to override
	[[dimension_overrides.dimensions]]
		name = "overworld"
		description = ""
		state = "In the Overworld"
		largeImageKey = "logo-overworld"
		largeImageText = "In the Overworld"
		smallImageKey = "fabric"
		smallImageText = "%mods% mods installed"

	[[dimension_overrides.dimensions]]
		name = "the_nether"
		description = ""
		state = "In the nether"
		largeImageKey = "logo-nether"
		largeImageText = "In the Nether"
		smallImageKey = "fabric"
		smallImageText = "%mods% mods installed"

	[[dimension_overrides.dimensions]]
		name = "the_end"
		description = ""
		state = "In the end"
		largeImageKey = "logo-end"
		largeImageText = "In the End"
		smallImageKey = "fabric"
		smallImageText = "%mods% mods installed"

