name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

jobs:
  Mac-Build:
    runs-on: macos-latest
    steps:
      - name: Download & Install TypeWriter
        run: |
          curl -L --output ./TypeWriter.zip --url https://github.com/Dot-lua/TypeWriter/releases/latest/download/TypeWriter-MacOs.zip
          tar -xf ./TypeWriter.zip
          ls
          chmod +x ./TypeWriter
          shopt -s expand_aliases
          ./TypeWriter
          '/Users/runner/Library/Application Support/TypeWriter//TypeWriter'
          rm ./TypeWriter.zip
          rm ./TypeWriter
          source ~/.bash_profiles
          
      - name: Clone repository
        run: |
          git clone https://github.com/CoreBytee/ModLoader/ ./
          ls
          
      - name: Build JavaHome
        run: |
          '/Users/runner/Library/Application Support/TypeWriter//TypeWriter' buildexecutable --input=./JavaHome/src/ --output=./
          ls
          
      - name: Build JavaRuntime
        run: |
          '/Users/runner/Library/Application Support/TypeWriter//TypeWriter' buildexecutable --input=./JavaRuntime/src/ --output=./
          ls
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: CubicLoader-Libraries-Mac
          path: ./.TypeWriter/Build/
          
  Windows-Build:
    runs-on: windows-latest
    steps:
      - name: Download & Install TypeWriter
        run: |
          curl -L --output ./TypeWriter.zip --url https://github.com/Dot-lua/TypeWriter/releases/latest/download/TypeWriter-Windows.zip
          tar -xf ./TypeWriter.zip
          ./TypeWriter.exe
          TypeWriter
          rm ./TypeWriter.zip
          rm ./TypeWriter.exe

      - name: Clone repository
        run: |
          git clone https://github.com/CoreBytee/ModLoader/ ./
          ls
          
      - name: Build JavaHome
        run: |
          TypeWriter buildexecutable --input=./JavaHome/src/ --output=./
          ls
          
      - name: Build JavaRuntime
        run: |
          TypeWriter buildexecutable --input=./JavaRuntime/src/ --output=./
          ls
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: CubicLoader-Libraries-Windows
          path: ./.TypeWriter/Build/
